@startuml
start
:User types "add sn/Tom pn/Hanks e/hanks@hotmail.com id/A00A p/98102932 a/Bukit View 9";
if () then ([isValidPhone and isValidEmail and isValidStudentName and isValidParentName and isUniqueId])
    :AddStudentCommandParser successfully parses
    user input and executes AddStudentCommand;
    :Student is added to model and an add success message
    is displayed;
else ([else])
:AddStudentCommandParser throws an error to user;
endif
stop
@enduml
